GET http://192.168.2.41:8080/get-balance/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwiZXhwaXJlIjoxNzIxMjcxNjk1LCJ1c2VySWQiOjB9.WfQxWk3k4gNLfPXhBadozIphBQRKqmaVN60Vn3fq1f8