GET http://192.168.2.41:8080/get-balance/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwiZXhwaXJlIjoxNzIxMTg5ODk5LCJ1c2VySWQiOjB9.VagI3razsVPZQMk5PVvAnUNju8LwEy2NaUBRzdHo5rg