GET http://192.168.2.41:8080/get-balance/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwiZXhwaXJlIjoxNzIxMjc3MTQwLCJ1c2VySWQiOjB9.GDeis4oIJSyiIjVmD4O0fs0o3fSKcNeMXitTh5aN_xw